# Generated by Django 6.0 on 2026-02-03 18:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views_count', models.IntegerField(default=0, editable=False)),
                ('phone_number_views_count', models.IntegerField(default=0, editable=False)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('vin', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='VIN must be 17 characters long and contain only allowed characters (A-H, J-N, P-R, S-Z, 0-9).', regex='^[A-HJ-NPR-Z0-9]{17}$')])),
                ('vehicle_type', models.CharField(choices=[('SDN', 'Sedan'), ('TK', 'Truck'), ('SUV', 'SUV')], default='SDN', max_length=3)),
                ('year', models.PositiveSmallIntegerField()),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('trim', models.CharField(blank=True, max_length=255, null=True)),
                ('mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('title_document', models.CharField(choices=[('CL', 'Clean'), ('RE', 'Rebuilt'), ('SA', 'Salvage')], default='SA', max_length=2)),
                ('fuel_type', models.CharField(choices=[('GAS', 'Gasoline'), ('DIS', 'Diesel'), ('HYB', 'Hybrid'), ('ELC', 'Electric')], default='GAS', max_length=3, null=True)),
                ('drive', models.CharField(choices=[('FWD', 'Front Wheel Drive'), ('RWD', 'Rear Wheel Drive'), ('AWD', 'All Wheel Drive'), ('4WD', 'Four Wheel Drive'), ('EAWD', 'Electric All Wheel Drive'), ('OTH', 'Other')], default='FWD', max_length=4)),
                ('transmission', models.CharField(choices=[('ATM', 'Automatic'), ('MAN', 'Manual'), ('CVT', 'CVT'), ('DTC', 'DTC'), ('ECVT', 'ECVT')], default='ATM', max_length=4)),
                ('engine', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('exterior_color', models.CharField(blank=True, choices=[('BLK', 'Black'), ('WHT', 'White'), ('BRW', 'Brown'), ('RED', 'Red'), ('GRN', 'Green'), ('BLU', 'Blue'), ('GRY', 'Grey')], max_length=3, null=True)),
                ('interior_color', models.CharField(blank=True, choices=[('BLK', 'Black'), ('WHT', 'White'), ('BRW', 'Brown'), ('RED', 'Red'), ('GRN', 'Green'), ('BLU', 'Blue'), ('GRY', 'Grey')], max_length=3, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('city_mpg', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hwy_mpg', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('sale_price', models.PositiveIntegerField(blank=True, null=True)),
                ('retail_price', models.PositiveIntegerField(blank=True, null=True)),
                ('carfax_pdf', models.FileField(blank=True, null=True, upload_to='carfax_pdfs/')),
                ('owners', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('AV', 'Available'), ('PE', 'Pending'), ('SO', 'Sold')], default='AV', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('is_promoted', models.BooleanField(default=False)),
                ('promoted_until', models.DateTimeField(blank=True, null=True)),
                ('promotion_priority', models.PositiveSmallIntegerField(default=0)),
                ('seller', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListingDamageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_image', models.ImageField(upload_to='listing_damage_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_images', to='inventory.listing')),
            ],
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_key', models.CharField(max_length=500)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.listing')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=50)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='inventory.listing')),
            ],
        ),
        migrations.CreateModel(
            name='ListingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='inventory.listing')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('reviewer', 'listing')},
            },
        ),
    ]
