# Generated by Django 6.0 on 2026-02-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_listingimage_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingimage',
            old_name='s3_key',
            new_name='original_s3_key',
        ),
        migrations.AddField(
            model_name='listingimage',
            name='large_s3_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='medium_s3_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='thumb_s3_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
