# Generated by Django 6.0 on 2026-02-12 20:15

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_s3_key_listingimage_original_s3_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='vin',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='VIN must be 17 characters long and contain only allowed characters (A-H, J-N, P-R, S-Z, 0-9).', regex='^[A-HJ-NPR-Z0-9]{17}$')]),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'available')), fields=('vin',), name='unique_available_vin'),
        ),
    ]
