# Generated by Django 6.0 on 2026-02-12 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_listing_vin_listing_unique_available_vin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='listing',
            name='unique_available_vin',
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'AV')), fields=('vin',), name='unique_available_vin'),
        ),
    ]
