# Generated by Django 6.0 on 2026-02-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_listing_unique_available_vin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingimage',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='listingimage',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
