# Generated by Django 6.0 on 2026-05-16 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_listingimage_options_listingimage_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleoption',
            name='option',
        ),
        migrations.RemoveField(
            model_name='vehicleoption',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='listing',
            name='options',
            field=models.ManyToManyField(blank=True, to='inventory.vehicleoption'),
        ),
        migrations.AddField(
            model_name='vehicleoption',
            name='icon',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vehicleoption',
            name='label',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='make',
            field=models.CharField(choices=[('BMW', 'BMW'), ('AUDI', 'Audi'), ('VOLKSWAGEN', 'Volkswagen'), ('SUBARU', 'Subaru'), ('HONDA', 'Honda'), ('MAZDA', 'Mazda'), ('FORD', 'Ford'), ('TOYOTA', 'Toyota'), ('CHEVROLET', 'Chevrolet'), ('NISSAN', 'Nissan')], max_length=30),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'listing')},
            },
        ),
        migrations.DeleteModel(
            name='ListingDamageImage',
        ),
    ]
