# Generated by Django 6.0 on 2026-07-07 20:56

import django.db.models.deletion
from django.db import migrations, models

INITIAL_MAKES = [
    "BMW", "Audi", "Volkswagen", "Subaru", "Honda",
    "Mazda", "Ford", "Toyota", "Chevrolet", "Nissan",
]


def seed_makes(apps, schema_editor):
    Make = apps.get_model("inventory", "Make")
    Make.objects.bulk_create([Make(name=name) for name in INITIAL_MAKES])


def unseed_makes(apps, schema_editor):
    Make = apps.get_model("inventory", "Make")
    Make.objects.filter(name__in=INITIAL_MAKES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_listingcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='listing',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='inventory.make'),
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='inventory.make')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('make', 'name')},
            },
        ),
        migrations.AlterField(
            model_name='listing',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='inventory.vehiclemodel'),
        ),
        migrations.RunPython(seed_makes, unseed_makes),
    ]
