# Generated by Django 6.0 on 2026-07-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_make_alter_listing_make_vehiclemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='exterior_color',
            field=models.CharField(blank=True, choices=[('BLK', 'Black'), ('WHT', 'White'), ('SIL', 'Silver'), ('GRY', 'Grey'), ('RED', 'Red'), ('BLU', 'Blue'), ('BRW', 'Brown'), ('TAN', 'Beige/Tan'), ('GRN', 'Green'), ('ORG', 'Orange'), ('YEL', 'Yellow'), ('GLD', 'Gold'), ('MAR', 'Maroon'), ('PUR', 'Purple')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='interior_color',
            field=models.CharField(blank=True, choices=[('BLK', 'Black'), ('WHT', 'White'), ('SIL', 'Silver'), ('GRY', 'Grey'), ('RED', 'Red'), ('BLU', 'Blue'), ('BRW', 'Brown'), ('TAN', 'Beige/Tan'), ('GRN', 'Green'), ('ORG', 'Orange'), ('YEL', 'Yellow'), ('GLD', 'Gold'), ('MAR', 'Maroon'), ('PUR', 'Purple')], max_length=3, null=True),
        ),
    ]
