# Generated by Django 6.0 on 2026-07-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_featuredlisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='vehicle_type',
            field=models.CharField(choices=[('SDN', 'Sedan'), ('TK', 'Truck'), ('SUV', 'SUV'), ('WGN', 'Wagon'), ('CPE', 'Coupe'), ('HBK', 'Hatchback'), ('VAN', 'Van')], default='SDN', max_length=3),
        ),
    ]
