# Generated by Django 6.0 on 2026-07-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_listing_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='alignment_report',
            field=models.FileField(blank=True, null=True, upload_to='alignment_reports/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='inspection_report',
            field=models.FileField(blank=True, null=True, upload_to='inspection_reports/'),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='photo_type',
            field=models.CharField(choices=[('gallery', 'Gallery'), ('before_repair', 'Before Repair')], default='gallery', max_length=20),
        ),
    ]
