# Generated by Django 6.0 on 2026-07-14 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_testdriverequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='phone_number_views_count',
            new_name='call_count',
        ),
    ]
