# Generated by Django 6.0 on 2026-07-22 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_rename_phone_number_views_count_listing_call_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='listing',
            name='unique_available_vin',
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('status', 'AV')), fields=('vin',), name='unique_available_vin'),
        ),
    ]
