# Generated by Django 6.0 on 2026-07-22 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_remove_listing_unique_available_vin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('FAKE_VIN', "VIN doesn't match the vehicle"), ('DUP_VIN', 'VIN is already listed on another ad'), ('MISLEADING', 'Listing details are misleading or inaccurate'), ('SOLD', 'Vehicle has already been sold elsewhere'), ('SCAM', 'Suspected scam or fraud'), ('HARASSMENT', 'Harassment or abusive behavior'), ('FAKE_PROFILE', 'Fake or impersonating profile'), ('INAPPROPRIATE', 'Inappropriate content'), ('SPAM', 'Spam'), ('OTHER', 'Other')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('RE', 'Reviewed'), ('DI', 'Dismissed')], default='PE', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='inventory.listing')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_filed', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('listing__isnull', False), ('seller__isnull', True)), models.Q(('listing__isnull', True), ('seller__isnull', False)), _connector='OR'), name='report_targets_exactly_one')],
            },
        ),
    ]
