# Generated by Django 6.0 on 2026-07-23 02:19

from django.db import migrations, models


def reassign_clean_titles(apps, schema_editor):
    # "Clean" is being dropped as a valid title_document choice (a salvage
    # marketplace's listings are never actually clean-titled) -- existing
    # rows tagged 'CL' would otherwise fail validation the next time they're
    # saved, since Listing.save() always calls full_clean().
    Listing = apps.get_model('inventory', 'Listing')
    Listing.objects.filter(title_document='CL').update(title_document='SA')


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_report'),
    ]

    operations = [
        migrations.RunPython(reassign_clean_titles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='listing',
            name='title_document',
            field=models.CharField(choices=[('RE', 'Rebuilt'), ('SA', 'Salvage')], default='SA', max_length=2),
        ),
    ]
