# Generated by Django 6.0 on 2026-07-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_listing_title_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('AV', 'Available'), ('PE', 'Pending'), ('SO', 'Sold')], default='AV', max_length=2),
        ),
    ]
