# Generated by Django 6.0 on 2026-07-24 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_listing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='make',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='inventory.make'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='inventory.vehiclemodel'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
