# Generated by Django 6.0 on 2026-07-24 18:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_alter_listing_make_alter_listing_model_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='listing',
            name='unique_available_vin',
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('status__in', ['AV', 'PE'])), fields=('vin',), name='unique_active_vin'),
        ),
    ]
