# Generated by Django 6.0 on 2026-07-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_remove_listing_unique_available_vin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicleoption',
            options={'ordering': ['category', 'label']},
        ),
        migrations.AddField(
            model_name='vehicleoption',
            name='category',
            field=models.CharField(choices=[('CMF', 'Comfort & Interior'), ('TEC', 'Technology & Infotainment'), ('SAF', 'Safety & Driver Assistance'), ('EXT', 'Exterior & Convenience'), ('PRF', 'Performance & Towing')], default='CMF', max_length=3),
        ),
    ]
