# Generated by Django 6.0 on 2026-07-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_seed_vehicle_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='has_warranty',
            field=models.BooleanField(default=False),
        ),
    ]
