# Generated by Django 6.0 on 2026-07-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_listing_has_warranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='title_document',
            field=models.CharField(choices=[('RE', 'Rebuilt'), ('SA', 'Salvage'), ('CT', 'Clean (Total Loss)')], default='SA', max_length=2),
        ),
    ]
