# Generated by Django 6.0 on 2026-07-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_alter_listing_title_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='renewal_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='renewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
