# Generated by Django 6.0 on 2026-07-30 21:11

from django.db import migrations, models


# Wagon/Coupe/Hatchback are being squashed into Sedan (see VehicleType on the
# Listing model) -- these are the only three being removed, so this is a
# direct code-to-code remap rather than needing to re-run VIN decoding.
BODY_STYLE_REMAP = {
    "WGN": "SDN",
    "CPE": "SDN",
    "HBK": "SDN",
}


def squash_body_styles(apps, schema_editor):
    Listing = apps.get_model("inventory", "Listing")
    for old_code, new_code in BODY_STYLE_REMAP.items():
        Listing.objects.filter(vehicle_type=old_code).update(vehicle_type=new_code)


def unsquash_body_styles(apps, schema_editor):
    # Irreversible -- once a Wagon/Coupe/Hatchback listing becomes a Sedan,
    # there's no record of which specific one it used to be.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_listing_renewal_count_listing_renewed_at'),
    ]

    operations = [
        migrations.RunPython(squash_body_styles, unsquash_body_styles),
        migrations.AlterField(
            model_name='listing',
            name='vehicle_type',
            field=models.CharField(choices=[('SDN', 'Sedan'), ('TK', 'Truck'), ('SUV', 'SUV'), ('VAN', 'Van')], default='SDN', max_length=3),
        ),
    ]
