# Generated by Django 6.0 on 2026-07-31 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_squash_body_styles'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='draft_saved',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
