# Generated by Django 6.0 on 2026-08-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_listing_draft_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='vehicle_type',
            field=models.CharField(choices=[('SDN', 'Sedan'), ('TK', 'Truck'), ('SUV', 'SUV'), ('VAN', 'Van'), ('OTH', 'Other')], default='SDN', max_length=3),
        ),
    ]
