# Generated by Django 6.0 on 2026-08-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_makemodelrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='expected_photo_count',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
