# Generated by Django 6.0 on 2026-08-08 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_listing_damage_photos_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingimage',
            name='descriptor',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
