# Generated by Django 6.0 on 2026-02-12 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='longitude',
        ),
    ]
