# Generated by Django 6.0 on 2026-07-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_show_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='offers_financing',
            field=models.BooleanField(default=False, help_text='Dealer offers in-house (buy here, pay here) financing.'),
        ),
    ]
