# Generated by Django 6.0 on 2026-07-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_is_verified_verificationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='offers_warranty',
            field=models.BooleanField(default=False, help_text='Dealer offers a warranty on their vehicles.'),
        ),
        migrations.AddField(
            model_name='user',
            name='warranty_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='warranty_duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
