# Generated by Django 6.0 on 2026-07-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_offers_warranty_user_warranty_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
