# Generated by Django 6.0 on 2026-07-29 19:27

from django.db import migrations, models


def blank_phones_to_null(apps, schema_editor):
    # Must run before the AlterField below adds the unique constraint --
    # multiple existing accounts have phone='' (blank, never filled in),
    # which would collide with each other as literal duplicate values. NULL
    # is exempt from a unique index (each one counts as distinct), '' is not.
    User = apps.get_model('users', 'User')
    User.objects.filter(phone='').update(phone=None)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_phone_verified'),
    ]

    operations = [
        # Column has to actually allow NULL before blank_phones_to_null can
        # write any -- then the unique constraint goes on last, once no
        # duplicate '' values are left for it to trip over.
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RunPython(blank_phones_to_null, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
