# Generated by Django 6.0 on 2026-07-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_locale',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('uk', 'Українська'), ('ru', 'Русский'), ('es', 'Español')], max_length=5, null=True),
        ),
    ]
