# Generated by Django 6.0 on 2026-07-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_preferred_locale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_locale',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('uk', 'Українська'), ('ru', 'Русский'), ('es', 'Español'), ('ro', 'Română (Moldova)')], max_length=5, null=True),
        ),
    ]
