# Generated by Django 6.0 on 2026-08-04 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_preferred_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('AP', 'Approved'), ('DE', 'Denied'), ('RE', 'Revoked')], default='PE', max_length=2)),
                ('key_prefix', models.CharField(blank=True, editable=False, max_length=12)),
                ('hashed_key', models.CharField(blank=True, db_index=True, editable=False, max_length=64)),
                ('note', models.TextField(blank=True, help_text='Why the user says they want API access.')),
                ('denial_reason', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_key', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
