# Generated by Django 6.0 on 2026-08-04 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('category', models.CharField(choices=[('BUG', 'Bug Report'), ('SUG', 'Suggestion'), ('OTH', 'Other')], default='SUG', max_length=3)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('context', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REV', 'In Review'), ('PLN', 'Planned'), ('RES', 'Resolved'), ('DEC', 'Declined')], default='NEW', max_length=3)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
