# Generated by Django 6.0 on 2026-08-04 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerChecklistCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name, e.g. "FileText".', max_length=50)),
                ('title_en', models.CharField(max_length=200)),
                ('title_uk', models.CharField(blank=True, max_length=200)),
                ('title_ru', models.CharField(blank=True, max_length=200)),
                ('title_es', models.CharField(blank=True, max_length=200)),
                ('title_ro', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Buyer checklist categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BuyerChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('text_en', models.TextField()),
                ('text_uk', models.TextField(blank=True)),
                ('text_ru', models.TextField(blank=True)),
                ('text_es', models.TextField(blank=True)),
                ('text_ro', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklist.buyerchecklistcategory')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
