# Generated by Django 6.0 on 2026-08-04 21:01

from django.db import migrations

# Seed content for the /checklist page. Kept as plain data here (rather than
# fixtures) so it runs automatically on any fresh deploy -- from here on,
# editing this content is expected to happen through the Django admin
# (see checklist/admin.py), not through further migrations.
CHECKLIST_DATA = [
    {
        "icon": "FileText",
        "title": {
            "en": "Understand the Title",
            "uk": "Розберіться в типі титулу",
            "ru": "Разберитесь в типе титула",
            "es": "Entienda el tipo de título",
            "ro": "Înțelegeți tipul de titlu",
        },
        "items": [
            {
                "en": "Know the difference between Salvage, Rebuilt, and Clean (Total Loss) titles.",
                "uk": "З'ясуйте різницю між титулами Аварійний (Salvage), Відновлений (Rebuilt) і Чистий (Повна загибель).",
                "ru": "Узнайте разницу между титулами Аварийный (Salvage), Восстановленный (Rebuilt) и Чистый (Полная гибель).",
                "es": "Conozca la diferencia entre los títulos De salvamento (Salvage), Reconstruido (Rebuilt) y Limpio (Pérdida Total).",
                "ro": "Aflați diferența dintre titlurile Avariat (Salvage), Recondiționat (Rebuilt) și Curat (daună totală).",
            },
            {
                "en": "Find out exactly why the vehicle was declared a total loss (collision, flood, theft, hail, fire).",
                "uk": "Дізнайтеся, чому автомобіль визнали повною загибеллю (ДТП, повінь, крадіжка, град, пожежа).",
                "ru": "Выясните, почему автомобиль признали полной гибелью (ДТП, наводнение, кража, град, пожар).",
                "es": "Averigüe exactamente por qué el vehículo fue declarado pérdida total (colisión, inundación, robo, granizo, incendio).",
                "ro": "Aflați exact de ce vehiculul a fost declarat daună totală (coliziune, inundație, furt, grindină, incendiu).",
            },
            {
                "en": "Check your state's requirements for re-registering a salvage or rebuilt vehicle.",
                "uk": "Перевірте вимоги вашого штату щодо повторної реєстрації автомобіля з аварійним або відновленим титулом.",
                "ru": "Проверьте требования вашего штата к повторной регистрации автомобиля с аварийным или восстановленным титулом.",
                "es": "Revise los requisitos de su estado para volver a registrar un vehículo de salvamento o reconstruido.",
                "ro": "Verificați cerințele statului dumneavoastră pentru reînmatricularea unui vehicul avariat sau recondiționat.",
            },
        ],
    },
    {
        "icon": "Search",
        "title": {
            "en": "Verify the Vehicle's History",
            "uk": "Перевірте історію автомобіля",
            "ru": "Проверьте историю автомобиля",
            "es": "Verifique el historial del vehículo",
            "ro": "Verificați istoricul vehiculului",
        },
        "items": [
            {
                "en": "Run the VIN through a vehicle history report (e.g. Carfax or AutoCheck).",
                "uk": "Замовте звіт про історію автомобіля за VIN-кодом (наприклад, Carfax або AutoCheck).",
                "ru": "Закажите отчёт об истории автомобиля по VIN-коду (например, Carfax или AutoCheck).",
                "es": "Genere un informe de historial del vehículo con el VIN (por ejemplo, Carfax o AutoCheck).",
                "ro": "Generați un raport de istoric al vehiculului pe baza VIN-ului (de exemplu, Carfax sau AutoCheck).",
            },
            {
                "en": "Confirm the VIN on the title matches the VIN on the vehicle itself (dashboard, door jamb, engine bay).",
                "uk": "Переконайтеся, що VIN-код у титулі збігається з VIN-кодом на самому автомобілі (панель приладів, дверна стійка, моторний відсік).",
                "ru": "Убедитесь, что VIN-код в титуле совпадает с VIN-кодом на самом автомобиле (панель приборов, дверная стойка, моторный отсек).",
                "es": "Confirme que el VIN del título coincide con el VIN del propio vehículo (tablero, marco de la puerta, compartimento del motor).",
                "ro": "Confirmați că VIN-ul de pe titlu corespunde cu VIN-ul de pe vehicul (bord, montant ușă, compartiment motor).",
            },
            {
                "en": "Check for flood damage, odometer rollback, or additional branding history.",
                "uk": "Перевірте наявність пошкоджень від повені, скручування одометра чи додаткових позначок в історії титулу.",
                "ru": "Проверьте наличие повреждений от наводнения, скрутки одометра или дополнительных отметок в истории титула.",
                "es": "Revise si hay daños por inundación, manipulación del odómetro u otras marcas en el historial del título.",
                "ro": "Verificați dacă există daune provocate de inundații, dare înapoi a kilometrajului sau alte mențiuni în istoricul titlului.",
            },
        ],
    },
    {
        "icon": "Wrench",
        "title": {
            "en": "Inspect Before You Buy",
            "uk": "Огляньте автомобіль перед покупкою",
            "ru": "Осмотрите автомобиль перед покупкой",
            "es": "Inspeccione antes de comprar",
            "ro": "Inspectați înainte de a cumpăra",
        },
        "items": [
            {
                "en": "See the vehicle in person whenever possible, rather than relying on photos alone.",
                "uk": "Оглядайте автомобіль особисто, коли це можливо, а не покладайтеся лише на фотографії.",
                "ru": "Осматривайте автомобиль лично, когда это возможно, а не полагайтесь только на фотографии.",
                "es": "Vea el vehículo en persona siempre que sea posible, en lugar de confiar solo en las fotos.",
                "ro": "Vedeți vehiculul personal ori de câte ori este posibil, în loc să vă bazați doar pe fotografii.",
            },
            {
                "en": "Get a professional pre-purchase inspection, especially for frame and structural integrity.",
                "uk": "Замовте професійний огляд перед покупкою, особливо перевірку рами та конструктивної цілісності.",
                "ru": "Закажите профессиональный осмотр перед покупкой, особенно проверку рамы и конструктивной целостности.",
                "es": "Consiga una inspección profesional previa a la compra, especialmente del chasis y la integridad estructural.",
                "ro": "Solicitați o inspecție profesională înainte de cumpărare, în special pentru șasiu și integritatea structurală.",
            },
            {
                "en": "Check for signs of water damage: musty smell, rust in unusual places, foggy headlights.",
                "uk": "Зверніть увагу на ознаки пошкодження водою: затхлий запах, іржа в нетипових місцях, запітнілі фари.",
                "ru": "Обратите внимание на признаки повреждения водой: затхлый запах, ржавчина в нетипичных местах, запотевшие фары.",
                "es": "Busque señales de daño por agua: olor a humedad, óxido en lugares inusuales, faros empañados.",
                "ro": "Verificați semnele de deteriorare cauzate de apă: miros de mucegai, rugină în locuri neobișnuite, faruri aburite.",
            },
            {
                "en": "Look for panel gaps or paint overspray that suggest prior collision repair.",
                "uk": "Перевірте зазори між панелями кузова та сліди перефарбування -- вони можуть свідчити про попередній ремонт після аварії.",
                "ru": "Проверьте зазоры между панелями кузова и следы перекраски -- они могут указывать на ремонт после аварии.",
                "es": "Fíjese en desajustes entre paneles o pintura con exceso de aspersión, que sugieren una reparación previa por colisión.",
                "ro": "Urmăriți spațiile inegale dintre panouri sau vopseaua aplicată în exces, care sugerează o reparație anterioară în urma unei coliziuni.",
            },
        ],
    },
    {
        "icon": "FileCheck",
        "title": {
            "en": "Review the Paperwork",
            "uk": "Перевірте документи",
            "ru": "Проверьте документы",
            "es": "Revise la documentación",
            "ro": "Verificați documentele",
        },
        "items": [
            {
                "en": "Ask the seller for repair records or receipts showing what was fixed.",
                "uk": "Попросіть у продавця документи або квитанції, що підтверджують виконаний ремонт.",
                "ru": "Попросите у продавца документы или квитанции, подтверждающие выполненный ремонт.",
                "es": "Pida al vendedor los registros o recibos de reparación que muestren qué se arregló.",
                "ro": "Cereți vânzătorului evidențele sau chitanțele de reparație care arată ce a fost reparat.",
            },
            {
                "en": "Request before-and-after photos of the repair work, if available.",
                "uk": "Запросіть фотографії до і після ремонту, якщо вони є.",
                "ru": "Запросите фотографии до и после ремонта, если они есть.",
                "es": "Solicite fotos del antes y el después de la reparación, si están disponibles.",
                "ro": "Solicitați fotografii înainte și după reparație, dacă sunt disponibile.",
            },
            {
                "en": "Confirm the seller's name matches the name on the title.",
                "uk": "Переконайтеся, що ім'я продавця збігається з іменем, зазначеним у титулі.",
                "ru": "Убедитесь, что имя продавца совпадает с именем, указанным в титуле.",
                "es": "Confirme que el nombre del vendedor coincide con el nombre del título.",
                "ro": "Confirmați că numele vânzătorului corespunde cu numele de pe titlu.",
            },
        ],
    },
    {
        "icon": "ShieldCheck",
        "title": {
            "en": "Plan for Insurance & Financing",
            "uk": "Продумайте страхування та фінансування",
            "ru": "Продумайте страхование и финансирование",
            "es": "Planifique el seguro y el financiamiento",
            "ro": "Planificați asigurarea și finanțarea",
        },
        "items": [
            {
                "en": "Confirm with your insurer that you can get coverage for a salvage or rebuilt title -- many limit these to liability-only.",
                "uk": "Уточніть у страхової компанії, чи можна застрахувати автомобіль з аварійним або відновленим титулом -- багато страховиків обмежують такі поліси лише цивільною відповідальністю.",
                "ru": "Уточните у страховой компании, можно ли застраховать автомобиль с аварийным или восстановленным титулом -- многие страховщики ограничивают такие полисы только гражданской ответственностью.",
                "es": "Confirme con su aseguradora que puede obtener cobertura para un título de salvamento o reconstruido -- muchas la limitan solo a responsabilidad civil.",
                "ro": "Confirmați cu asigurătorul dumneavoastră că puteți obține acoperire pentru un titlu avariat sau recondiționat -- multe companii limitează acoperirea doar la răspundere civilă.",
            },
            {
                "en": "Know that financing a salvage-titled vehicle is harder to find than for a clean title.",
                "uk": "Майте на увазі, що знайти фінансування для автомобіля з аварійним титулом складніше, ніж для автомобіля з чистим титулом.",
                "ru": "Учитывайте, что найти финансирование для автомобиля с аварийным титулом сложнее, чем для автомобиля с чистым титулом.",
                "es": "Tenga en cuenta que financiar un vehículo con título de salvamento es más difícil que uno con título limpio.",
                "ro": "Rețineți că finanțarea unui vehicul cu titlu avariat este mai greu de obținut decât pentru unul cu titlu curat.",
            },
            {
                "en": "Get a realistic resale-value expectation -- salvage and rebuilt vehicles are worth noticeably less.",
                "uk": "Реалістично оцінюйте вартість перепродажу -- автомобілі з аварійним і відновленим титулом коштують помітно менше.",
                "ru": "Реалистично оценивайте стоимость перепродажи -- автомобили с аварийным и восстановленным титулом стоят заметно меньше.",
                "es": "Tenga una expectativa realista del valor de reventa -- los vehículos de salvamento y reconstruidos valen notablemente menos.",
                "ro": "Aveți o așteptare realistă privind valoarea de revânzare -- vehiculele avariate și recondiționate valorează considerabil mai puțin.",
            },
        ],
    },
    {
        "icon": "Landmark",
        "title": {
            "en": "Check Registration Requirements",
            "uk": "Перевірте вимоги щодо реєстрації",
            "ru": "Проверьте требования к регистрации",
            "es": "Revise los requisitos de registro",
            "ro": "Verificați cerințele de înmatriculare",
        },
        "items": [
            {
                "en": "Many states require a separate salvage/rebuilt vehicle inspection before you can register and drive it.",
                "uk": "У багатьох штатах перед реєстрацією та початком експлуатації потрібен окремий огляд автомобіля з аварійним або відновленим титулом.",
                "ru": "Во многих штатах перед регистрацией и началом эксплуатации требуется отдельный осмотр автомобиля с аварийным или восстановленным титулом.",
                "es": "Muchos estados exigen una inspección separada del vehículo de salvamento o reconstruido antes de poder registrarlo y conducirlo.",
                "ro": "Multe state necesită o inspecție separată a vehiculului avariat/recondiționat înainte de a-l putea înmatricula și conduce.",
            },
            {
                "en": "Look up your state's specific DMV requirements before you commit to buying.",
                "uk": "Дізнайтеся конкретні вимоги DMV вашого штату, перш ніж вирішити купувати.",
                "ru": "Узнайте конкретные требования DMV вашего штата, прежде чем решить купить.",
                "es": "Consulte los requisitos específicos del DMV de su estado antes de comprometerse a comprar.",
                "ro": "Consultați cerințele specifice ale instituției auto din statul dumneavoastră înainte de a vă angaja să cumpărați.",
            },
        ],
    },
    {
        "icon": "MessageCircleQuestion",
        "title": {
            "en": "Ask the Seller the Right Questions",
            "uk": "Поставте продавцю правильні запитання",
            "ru": "Задайте продавцу правильные вопросы",
            "es": "Hágale al vendedor las preguntas correctas",
            "ro": "Adresați vânzătorului întrebările potrivite",
        },
        "items": [
            {
                "en": "Why was the vehicle totaled, and what exactly was repaired?",
                "uk": "Чому автомобіль визнали повною загибеллю і що саме відремонтували?",
                "ru": "Почему автомобиль признали полной гибелью и что именно отремонтировали?",
                "es": "¿Por qué se declaró pérdida total el vehículo y qué se reparó exactamente?",
                "ro": "De ce a fost declarat vehiculul daună totală și ce anume a fost reparat?",
            },
            {
                "en": "Can I see the seller's rating and reviews before buying?",
                "uk": "Чи можу я побачити рейтинг і відгуки продавця перед покупкою?",
                "ru": "Могу ли я увидеть рейтинг и отзывы продавца перед покупкой?",
                "es": "¿Puedo ver la calificación y las reseñas del vendedor antes de comprar?",
                "ro": "Pot vedea evaluarea și recenziile vânzătorului înainte de a cumpăra?",
            },
            {
                "en": "Is the seller willing to answer questions and provide documentation?",
                "uk": "Чи готовий продавець відповідати на запитання та надавати документи?",
                "ru": "Готов ли продавец отвечать на вопросы и предоставить документы?",
                "es": "¿Está el vendedor dispuesto a responder preguntas y proporcionar documentación?",
                "ro": "Este vânzătorul dispus să răspundă la întrebări și să furnizeze documente?",
            },
        ],
    },
]


def seed_checklist(apps, schema_editor):
    Category = apps.get_model("checklist", "BuyerChecklistCategory")
    Item = apps.get_model("checklist", "BuyerChecklistItem")

    for cat_index, cat_data in enumerate(CHECKLIST_DATA):
        category = Category.objects.create(
            order=cat_index,
            icon=cat_data["icon"],
            title_en=cat_data["title"]["en"],
            title_uk=cat_data["title"]["uk"],
            title_ru=cat_data["title"]["ru"],
            title_es=cat_data["title"]["es"],
            title_ro=cat_data["title"]["ro"],
        )
        for item_index, item_data in enumerate(cat_data["items"]):
            Item.objects.create(
                category=category,
                order=item_index,
                text_en=item_data["en"],
                text_uk=item_data["uk"],
                text_ru=item_data["ru"],
                text_es=item_data["es"],
                text_ro=item_data["ro"],
            )


def unseed_checklist(apps, schema_editor):
    Category = apps.get_model("checklist", "BuyerChecklistCategory")
    Category.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_checklist, unseed_checklist),
    ]
