# Generated by Django 6.0 on 2026-08-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_seed_buyer_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerchecklistitem',
            name='note_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='buyerchecklistitem',
            name='note_es',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='buyerchecklistitem',
            name='note_ro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='buyerchecklistitem',
            name='note_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='buyerchecklistitem',
            name='note_uk',
            field=models.TextField(blank=True),
        ),
    ]
