# Generated by Django 6.0 on 2026-08-04 21:26

from django.db import migrations

# Replaces the placeholder 7-category/21-item seed from 0002 with a single,
# curated 7-item checklist supplied directly by the site owner -- see the
# note on item 6 below, which needed its own supplementary field (see
# BuyerChecklistItem.note_en in 0003) since it's a caveat rather than part
# of the main instruction.
ITEMS = [
    {
        "en": "Know the reason for total loss.",
        "uk": "З'ясуйте причину визнання автомобіля повною загибеллю.",
        "ru": "Выясните причину признания автомобиля полной гибелью.",
        "es": "Conozca el motivo por el que el vehículo fue declarado pérdida total.",
        "ro": "Aflați motivul pentru care vehiculul a fost declarat daună totală.",
    },
    {
        "en": "Check your state's requirements and process for registering a salvage/rebuilt vehicle.",
        "uk": "Перевірте вимоги та процедуру вашого штату для реєстрації автомобіля з аварійним/відновленим титулом.",
        "ru": "Проверьте требования и порядок регистрации автомобиля с аварийным/восстановленным титулом в вашем штате.",
        "es": "Revise los requisitos y el proceso de su estado para registrar un vehículo de salvamento/reconstruido.",
        "ro": "Verificați cerințele și procesul statului dumneavoastră pentru înmatricularea unui vehicul avariat/recondiționat.",
    },
    {
        "en": "Confirm the VIN on the title matches the VIN on the vehicle.",
        "uk": "Переконайтеся, що VIN-код у титулі збігається з VIN-кодом на автомобілі.",
        "ru": "Убедитесь, что VIN-код в титуле совпадает с VIN-кодом на автомобиле.",
        "es": "Confirme que el VIN del título coincide con el VIN del vehículo.",
        "ro": "Confirmați că VIN-ul de pe titlu corespunde cu VIN-ul de pe vehicul.",
    },
    {
        "en": "Check for flood damage, odometer rollback, or additional branding history.",
        "uk": "Перевірте наявність пошкоджень від повені, скручування одометра чи додаткових позначок в історії титулу.",
        "ru": "Проверьте наличие повреждений от наводнения, скрутки одометра или дополнительных отметок в истории титула.",
        "es": "Revise si hay daños por inundación, manipulación del odómetro u otras marcas en el historial del título.",
        "ro": "Verificați dacă există daune provocate de inundații, dare înapoi a kilometrajului sau alte mențiuni în istoricul titlului.",
    },
    {
        "en": "Get a pre-purchase inspection.",
        "uk": "Замовте огляд автомобіля перед покупкою.",
        "ru": "Закажите осмотр автомобиля перед покупкой.",
        "es": "Consiga una inspección previa a la compra.",
        "ro": "Solicitați o inspecție înainte de cumpărare.",
    },
    {
        "en": "Confirm with your insurer that you can get coverage for a salvage/rebuilt vehicle.",
        "uk": "Уточніть у страхової компанії, чи можна застрахувати автомобіль з аварійним/відновленим титулом.",
        "ru": "Уточните у своей страховой компании, можно ли застраховать автомобиль с аварийным/восстановленным титулом.",
        "es": "Confirme con su aseguradora que puede obtener cobertura para un vehículo de salvamento/reconstruido.",
        "ro": "Confirmați cu asigurătorul dumneavoastră că puteți obține acoperire pentru un vehicul avariat/recondiționat.",
        "note": {
            "en": "As of August 2026, every major insurer except Allstate offers comprehensive & collision coverage for salvage/rebuilt titles.",
            "uk": "Станом на серпень 2026 року всі великі страховики, крім Allstate, пропонують повне та комбіноване страхування (comprehensive & collision) для автомобілів з аварійним/відновленим титулом.",
            "ru": "По состоянию на август 2026 года все крупные страховщики, кроме Allstate, предлагают полное и комбинированное страхование (comprehensive & collision) для автомобилей с аварийным/восстановленным титулом.",
            "es": "A partir de agosto de 2026, todas las principales aseguradoras excepto Allstate ofrecen cobertura contra todo riesgo y por colisión (comprehensive & collision) para títulos de salvamento/reconstruidos.",
            "ro": "Începând cu august 2026, toți asigurătorii majori, cu excepția Allstate, oferă acoperire comprehensive & collision pentru titlurile avariate/recondiționate.",
        },
    },
    {
        "en": "Compare prices against the same vehicle with a clean title.",
        "uk": "Порівняйте ціну з такою ж моделлю, що має чистий титул.",
        "ru": "Сравните цену с такой же моделью с чистым титулом.",
        "es": "Compare el precio con el mismo vehículo con título limpio.",
        "ro": "Comparați prețul cu același vehicul cu titlu curat.",
    },
]

CATEGORY_TITLE = {
    "en": "Before You Buy",
    "uk": "Перед покупкою",
    "ru": "Перед покупкой",
    "es": "Antes de comprar",
    "ro": "Înainte de a cumpăra",
}


def replace_checklist(apps, schema_editor):
    Category = apps.get_model("checklist", "BuyerChecklistCategory")
    Item = apps.get_model("checklist", "BuyerChecklistItem")

    # Clears out the placeholder 7-category seed from 0002 entirely --
    # cascades to its items too.
    Category.objects.all().delete()

    category = Category.objects.create(
        order=0,
        icon="ListChecks",
        title_en=CATEGORY_TITLE["en"],
        title_uk=CATEGORY_TITLE["uk"],
        title_ru=CATEGORY_TITLE["ru"],
        title_es=CATEGORY_TITLE["es"],
        title_ro=CATEGORY_TITLE["ro"],
    )

    for index, item_data in enumerate(ITEMS):
        note = item_data.get("note", {})
        Item.objects.create(
            category=category,
            order=index,
            text_en=item_data["en"],
            text_uk=item_data["uk"],
            text_ru=item_data["ru"],
            text_es=item_data["es"],
            text_ro=item_data["ro"],
            note_en=note.get("en", ""),
            note_uk=note.get("uk", ""),
            note_ru=note.get("ru", ""),
            note_es=note.get("es", ""),
            note_ro=note.get("ro", ""),
        )


def noop_reverse(apps, schema_editor):
    # Not reversible back to the old placeholder content -- this migration's
    # forwards is a full content replacement, not a diff. Reversing just
    # clears the curated content rather than trying to resurrect 0002's data.
    Category = apps.get_model("checklist", "BuyerChecklistCategory")
    Category.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_buyerchecklistitem_note_en_and_more'),
    ]

    operations = [
        migrations.RunPython(replace_checklist, noop_reverse),
    ]
