# Generated by Django 6.0 on 2026-08-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0004_replace_with_curated_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerchecklistitem',
            name='icon',
            field=models.CharField(blank=True, help_text='Lucide icon name, e.g. "Wrench".', max_length=50),
        ),
    ]
