# Generated by Django 6.0 on 2026-08-04 21:39

from django.db import migrations

# Matched by `order` (stable -- see 0004_replace_with_curated_checklist,
# which set order 0..6 in this exact sequence) rather than by text, so this
# doesn't break if an admin has since edited the wording.
ICONS_BY_ORDER = {
    0: "FileSearch",     # Know the reason for total loss.
    1: "Landmark",        # State registration requirements.
    2: "ScanLine",         # VIN on title matches VIN on vehicle.
    3: "Droplets",         # Flood damage / odometer rollback / branding.
    4: "Wrench",            # Pre-purchase inspection.
    5: "ShieldCheck",        # Insurance coverage.
    6: "Scale",                # Compare price against a clean-title equivalent.
}


def set_icons(apps, schema_editor):
    Item = apps.get_model("checklist", "BuyerChecklistItem")
    for order, icon in ICONS_BY_ORDER.items():
        Item.objects.filter(order=order).update(icon=icon)


def clear_icons(apps, schema_editor):
    Item = apps.get_model("checklist", "BuyerChecklistItem")
    Item.objects.filter(order__in=ICONS_BY_ORDER.keys()).update(icon="")


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0005_buyerchecklistitem_icon'),
    ]

    operations = [
        migrations.RunPython(set_icons, clear_icons),
    ]
