"""
Django settings for onlysalvage_api project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import platform
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Loads onlysalvage_api/.env (gitignored) into the real process environment,
# same as if they'd been set in the shell -- every secret below is still read
# via plain os.environ.get(...), this just gives local dev a file to put them
# in instead of requiring real environment variables. Does nothing in
# production if that file doesn't exist there (real env vars take over).
from dotenv import load_dotenv
load_dotenv(BASE_DIR / ".env")

# Only needed on Windows dev machines with a manual OSGeo4W install -- on
# Linux (EC2, CI, any other dev's machine) GeoDjango finds libgdal/libgeos
# on the system loader path on its own once installed via the OS package
# manager (e.g. `apt-get install gdal-bin libgeos-dev`), so setting an
# explicit (and Windows-only-valid) path there would just break startup.
if platform.system() == "Windows":
    GDAL_LIBRARY_PATH = os.environ.get(
        "GDAL_LIBRARY_PATH",
        r"C:\Users\Ridgeline\AppData\Local\Programs\OSGeo4W\bin\gdal311.dll",
    )
    GEOS_LIBRARY_PATH = os.environ.get(
        "GEOS_LIBRARY_PATH",
        r"C:\Users\Ridgeline\AppData\Local\Programs\OSGeo4W\bin\geos_c.dll",
    )

# The OSGeo4W install's own share/proj/proj.db is stale relative to its GDAL
# DLL (mismatched PROJ database layout version), which makes any EPSG lookup
# -- e.g. transforming a PointField to SRID 4326 -- raise GDALException: OGR
# failure. pyproj bundles its own up-to-date, self-consistent proj.db, so we
# point PROJ at that instead of relying on the OSGeo4W one.
import pyproj
_PROJ_DATA_DIR = pyproj.datadir.get_data_dir()
os.environ["PROJ_LIB"] = _PROJ_DATA_DIR
os.environ["PROJ_DATA"] = _PROJ_DATA_DIR


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret! Required
# via env with no fallback -- see .env.example -- so a misconfigured deploy
# fails loudly at startup instead of silently running on a key anyone with
# repo access already knows. Generate a fresh one for production specifically
# (never reuse the local-dev value from .env) with:
#   python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False (fail-safe) -- local dev sets DJANGO_DEBUG=True in .env
# explicitly, so a forgotten env var in production means *more* locked down,
# not a debug page leaking source/settings to every visitor.
DEBUG = os.environ.get("DJANGO_DEBUG", "False") == "True"

if DEBUG:
    # Local/LAN dev -- also covers hitting the API directly by IP from
    # another device on the network (phone, etc.), same reasoning as
    # CORS_ALLOW_ALL_ORIGINS below.
    ALLOWED_HOSTS = ["*"]
else:
    ALLOWED_HOSTS = [h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',

    'users',
    'inventory',
    'publicapi',
    'checklist',

    'django_filters',

    'rest_framework',
    'rest_framework_simplejwt',

    'storages',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_CREDENTIALS = True

# In dev, any device on the LAN might load the frontend from a different IP
# each time (new device, DHCP lease renewal, etc.) -- rather than hand-maintain
# a fixed list of origins that breaks the moment that changes, just allow any
# origin while DEBUG is on (django-cors-headers still correctly echoes back
# the specific request origin rather than "*", which is what's actually
# required for CORS_ALLOW_CREDENTIALS to work). Production keeps a real list.
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    # Comma-separated, e.g. "https://onlysalvage.com,https://www.onlysalvage.com".
    CORS_ALLOWED_ORIGINS = [o.strip() for o in os.environ.get("CORS_ALLOWED_ORIGINS", "").split(",") if o.strip()]

FRONTEND_URL = os.environ.get("FRONTEND_URL", "http://localhost:3000")

GOOGLE_OAUTH_CLIENT_ID = os.environ.get(
  "GOOGLE_OAUTH_CLIENT_ID",
  "439609537125-5h9v3ll3v4ademikp9t6id4to6ick1hb.apps.googleusercontent.com",
)

# No fallback -- unlike GOOGLE_OAUTH_CLIENT_ID above (which is safe to embed
# since OAuth client IDs are sent to the browser anyway), this is a billable
# key with no usage restriction baked into it, so it must not live in source.
GOOGLE_PLACES_API_KEY = os.environ.get("GOOGLE_PLACES_API_KEY", "")

# Defaults to the Places key since API keys on the same Google Cloud project
# commonly work across multiple enabled APIs -- set GOOGLE_TRANSLATE_API_KEY
# explicitly if the Cloud Translation API ends up needing its own key
# (e.g. once the Places key gets restricted to just the Places API).
GOOGLE_TRANSLATE_API_KEY = os.environ.get("GOOGLE_TRANSLATE_API_KEY", GOOGLE_PLACES_API_KEY)

# Twilio Verify (phone number verification). TWILIO_ACCOUNT_SID/AUTH_TOKEN
# are used purely as HTTP Basic Auth credentials against the Verify REST
# API -- Twilio accepts either the real Account SID + Auth Token, or an API
# Key SID + Secret pair (SK.../...) for this, both work identically here.
# TWILIO_VERIFY_SERVICE_SID is a separate resource that has to be created
# once in the Twilio Console (Verify > Services) -- there's no default for it.
TWILIO_ACCOUNT_SID = os.environ.get("TWILIO_ACCOUNT_SID", "")
TWILIO_AUTH_TOKEN = os.environ.get("TWILIO_AUTH_TOKEN", "")
TWILIO_VERIFY_SERVICE_SID = os.environ.get("TWILIO_VERIFY_SERVICE_SID", "")

# Master switch for requiring phone verification at registration (see
# UserSerializer.validate() in users/api/serializers.py) -- off by default.
# Flip to "True" to restore the original behavior (phone required + must be
# verified via SendRegistrationPhoneCodeView/CheckRegistrationPhoneCodeView
# before an account can be created) with no other changes needed. The
# frontend has its own mirrored NEXT_PUBLIC_PHONE_VERIFICATION_ENABLED (see
# onlysalvage_frontend/.env.example) that must be flipped together with this
# one -- it controls whether the sign-up/settings UI even shows the phone
# verification step, independent of this backend-side enforcement.
PHONE_VERIFICATION_ENABLED = os.environ.get("PHONE_VERIFICATION_ENABLED", "False") == "True"

# Delivers /support page ContactMessage submissions (see users/utils/telegram.py)
# straight to a Telegram chat instead of email. TELEGRAM_CHAT_ID is whichever
# chat should receive them -- a personal DM with the bot, or a group it's been
# added to -- found by messaging the bot once and reading the `chat.id` off
# https://api.telegram.org/bot<token>/getUpdates. Sending is skipped
# (ContactMessage rows are still saved either way) until both are set.
TELEGRAM_BOT_API_TOKEN = os.environ.get("TELEGRAM_BOT_API_TOKEN", "")
TELEGRAM_CHAT_ID = os.environ.get("TELEGRAM_CHAT_ID", "")

# No SMTP configured yet -- prints emails to the console instead of sending them.
# Swap for a real backend (SES, SMTP, etc.) once credentials are available.
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
DEFAULT_FROM_EMAIL = "OnlySalvage <no-reply@onlysalvage.com>"
# Same address the frontend's /support page shows for direct contact --
# SiteFeedbackView notifies here too, so bug reports/suggestions land
# alongside everything else already going to this inbox.
SUPPORT_EMAIL = "support@onlysalvage.com"

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}

ROOT_URLCONF = 'onlysalvage_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'onlysalvage_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DJANGO_DB_HOST unset/"local" -> local Docker PostGIS (fast, no network
# hop). Set DJANGO_DB_HOST=aws to point at the AWS RDS instance instead --
# its real hostname comes from DJANGO_DB_HOST_AWS (required in that case),
# never hardcoded here. Any other value is used directly as the hostname,
# so production just sets DJANGO_DB_HOST to the real RDS endpoint.
_db_host_env = os.environ.get("DJANGO_DB_HOST", "local")
if _db_host_env == "local":
    _DB_HOST = 'localhost'
elif _db_host_env == "aws":
    _DB_HOST = os.environ["DJANGO_DB_HOST_AWS"]
else:
    _DB_HOST = _db_host_env

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.environ.get("DJANGO_DB_NAME", "postgres"),
        'USER': os.environ.get("DJANGO_DB_USER", "postgres"),
        'PASSWORD': os.environ.get("DJANGO_DB_PASSWORD", "test-password-for-onlysalvage"),
        'HOST': _DB_HOST,
        'PORT': os.environ.get("DJANGO_DB_PORT", "5432"),
        # Without this, Django opens a brand-new TCP connection + Postgres auth
        # handshake on every single request. That's cheap on a local DB but a
        # real fixed cost per request once the DB is remote (AWS here).
        'CONN_MAX_AGE': 60,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = "users.User"

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    "staticfiles": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
}

AWS_STORAGE_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME", "onlysalvage-dev-media")
AWS_S3_REGION_NAME = os.environ.get("AWS_S3_REGION_NAME", "us-east-1")

MEDIA_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/"
MEDIA_BASE_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/"

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_STORAGE = "storages.backends.s3boto3.S3StaticStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,

    "DEFAULT_AUTHENTICATION_CLASSES": (
        'onlysalvage_api.authentication.CookieJWTAuthentication',
    ),

    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend"
    ],

    # Baseline rate limiting for every endpoint that doesn't already have its
    # own scoped throttle below -- without this, login in particular
    # (CookieTokenObtainPairView) had zero rate limiting at all, i.e. no
    # bound on password-brute-force attempts against a single account.
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],

    "DEFAULT_THROTTLE_RATES": {
        # Generous baseline for ordinary browsing/API use -- scoped
        # throttles below override this for anything more sensitive.
        "anon": "100/min",
        "user": "300/min",
        # Login specifically -- IP-keyed via CookieTokenObtainPairView's own
        # throttle_classes, tighter than the anon default above since this
        # is exactly what a password-brute-force attempt would hit.
        "login": "10/min",
        # TranslateView is public and each call costs real money against the
        # Google Translate API -- bounds how much an anonymous IP can spend.
        "translate": "20/min",
        # Phone verification sends a real SMS through Twilio per call --
        # bounds how many one account can trigger.
        "phone-verify": "5/min",
        # Registration-time phone verification -- IP-keyed since there's no
        # account yet. Still worth bounding even though it's free right now
        # (console-printed code): it's the only thing standing between a
        # script and creating unlimited pending codes/verified-phone cache
        # entries once this is on Twilio for real.
        "registration-phone": "10/min",
        # The public v1 API (see the `publicapi` app) -- keyed per-user by
        # ApiKeyRateThrottle, so one integration's traffic can't starve
        # another's even if both somehow shared a token.
        "api-key": "120/min",
        # SiteFeedbackView is public (no account required to report a bug)
        # and sends a real email per submission -- IP-keyed bound against spam.
        "feedback": "5/hour",
        # ContactMessageView -- public, triggers a Telegram send per call.
        "contact": "5/hour",
    },
}

CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://localhost:6379/0")

_redis_cache_url = os.environ.get("REDIS_CACHE_URL")
if _redis_cache_url:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": _redis_cache_url,
        }
    }
# else: falls back to Django's default LocMemCache -- fine for local
# `runserver` (a single process, so there's no other worker to disagree
# about what's cached) but NOT safe once gunicorn runs multiple worker
# processes in production: users/utils/phone.py's send_phone_code caches a
# code in whichever worker handled that request, and check_phone_code reads
# it back in whichever worker (possibly a different one) handles the next
# request -- silently wrong/expired-looking codes without a shared cache.
# Set REDIS_CACHE_URL (a different Redis DB index than CELERY_BROKER_URL
# above, e.g. redis://host:6379/1) in production so every worker shares one.


# Security headers/cookie flags -- meaningful once DEBUG=False; harmless to
# compute in dev too since they just end up False/0 there (the dev server
# runs over plain HTTP with no proxy in front of it).
#
# SECURE_SSL_REDIRECT is deliberately NOT tied to DEBUG like the others below
# -- nginx (see deploy/nginx.conf) already 301s every external HTTP request
# to HTTPS before Django ever sees it, so this would be pure redundancy for
# real traffic. Worse, it actively breaks the internal Next.js -> Django
# calls (INTERNAL_API_URL, see onlysalvage_frontend/lib/apiUrl.ts), which
# deliberately go straight to gunicorn's loopback port over plain HTTP with
# no X-Forwarded-Proto header (that hop never touches nginx) -- Django would
# "helpfully" 301 those to https://127.0.0.1:8001/..., which doesn't exist,
# and Node's fetch would then throw a raw TLS ClientHello at gunicorn's
# plain-HTTP listener (shows up in gunicorn's log as a garbled "Invalid HTTP
# method"). Leave this False; DJANGO_ALLOWED_HOSTS + the other settings here
# still fully protect real external traffic.
SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_HSTS_SECONDS = 0 if DEBUG else 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
# nginx terminates TLS and forwards to gunicorn over plain HTTP internally --
# without this, Django can't tell the original request was HTTPS and
# SECURE_SSL_REDIRECT above would redirect-loop forever.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Django's own CSRF check compares the request's Origin against this list for
# any unsafe (POST/PUT/PATCH/DELETE) request -- separate from
# CORS_ALLOWED_ORIGINS above, which only governs cross-origin browser fetches.
# Comma-separated, e.g. "https://onlysalvage.com,https://www.onlysalvage.com".
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()]

# Plain console logging -- correct (not a placeholder) for how this actually
# runs in production: as a systemd service, so anything written to
# stdout/stderr is already captured by journald (`journalctl -u
# onlysalvage-api`) without needing a file handler or log-shipping config here.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": os.environ.get("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
    },
}